import type { ProFormaInput } from '@/types/proforma'

export function defaultProFormaInput(): ProFormaInput {
  return {
    property: {
      propertyName: '', address: '', city: '', state: '', zipCode: '',
      county: '', msa: '', submarket: '', apn: '',
      propertyType: 'multifamily', propertyClass: 'B',
      constructionType: 'wood-frame', yearBuilt: 2000, yearRenovated: 0,
      totalUnits: 10, totalSqft: 10000, netRentableSqft: 9500,
      commonAreaSqft: 500, lotSizeSqft: 15000, lotSizeAcres: 0.34,
      stories: 2, numberOfBuildings: 1,
      parkingSpaces: 15, parkingType: 'surface', coveredSpaces: 0, garageSpaces: 0,
      utilitySetup: 'master-metered', laundryType: 'common',
      hasElevator: false, hvacType: 'Central HVAC', roofType: 'Flat / TPO',
      roofAge: 5, plumbingAge: 20, electricalAge: 20,
      zoning: '', floodZone: 'X', seismicZone: '', currentOccupancy: 95,
      hasPool: false, hasFitnessCtr: false, hasDogPark: false,
      hasCoworking: false, hasEVCharging: false, hasSmartHome: false,
      hasGatedAccess: false, hasConcierge: false, amenitiesNotes: '',
      walkScore: 70, transitScore: 60, bikeScore: 50,
      schoolRating: 7, crimeIndex: 40,
      unitMix: [
        { id: '1', unitType: '1BR/1BA', unitCount: 6, sqft: 750, marketRent: 1500, currentRent: 1400, occupied: 6, leaseExpiration: '' },
        { id: '2', unitType: '2BR/1BA', unitCount: 4, sqft: 950, marketRent: 1800, currentRent: 1700, occupied: 4, leaseExpiration: '' },
      ],
      commercialTenants: [],
    },
    acquisition: {
      purchasePrice: 2000000, closingCosts: 1, brokerFeePercent: 0,
      legalFees: 5000, titleInsurance: 3000, transferTax: 5000,
      environmentalStudy: 2500, surveyAndEngineering: 1500,
      propertyInspection: 1200, appraisalFee: 3500, earnestMoneyDeposit: 50000,
      immediateCapEx: 50000, acquisitionFee: 1, organizationCosts: 10000,
      workingCapitalReserve: 25000, lenderFeeAtClose: 0, otherAcquisitionCosts: 2000,
    },
    financing: {
      useFinancing: true,
      loans: [{
        id: '1', label: 'Senior Loan', loanAmount: 1400000,
        interestRate: 6.5, amortizationYears: 30, ioPeriodYears: 2, loanTermYears: 10,
        isFloating: false, spread: 0, floorRate: 0,
        originationFee: 1, exitFee: 0,
        extensionOptions: 0, extensionMonths: 0, rateCap: 0,
        recourseType: 'non-recourse', isPersonalGuarantee: false,
        prepaymentType: 'none', prepaymentPenalty: 0,
      }],
      equityContribution: 660000,
    },
    income: {
      vacancyRate: 5, creditLoss: 1, concessions: 0,
      physicalOccupancy: 95, economicOccupancy: 93,
      hasRUBS: false, rubsMonthlyPerUnit: 0,
      petFeeMonthly: 0, petDeposit: 0, petFeePctUnits: 0,
      parkingIncome: 0, coveredParkingPremium: 0, garageIncome: 0,
      storageIncome: 0, laundryIncome: 200,
      applicationFees: 0, lateFees: 0, nsfFees: 0,
      moveInFees: 0, guestSuiteIncome: 0, vendingIncome: 0,
      billboardCellTower: 0, utilityReimbursement: 0,
      shortTermRentalIncome: 0,
      monthToMonthPremium: 0, monthToMonthPctUnits: 0,
      internetBulkBilling: 0,
      otherIncome: [
        { id: '1', label: 'Parking', annualAmount: 6000, growthRate: 2 },
      ],
      rentGrowthRate: 3, otherIncomeGrowthRate: 2,
    },
    expenses: {
      propertyTaxes: 24000, specialAssessments: 0,
      propertyInsurance: 10000, liabilityInsurance: 2000, floodInsurance: 0,
      earthquakeInsurance: 0, umbrellaPolicy: 500, workersComp: 800,
      electricity: 4000, gas: 1500, water: 3000, sewer: 1500, trash: 1200, cableInternet: 0,
      repairsAndMaintenance: 12000, plumbingRepairs: 1500, electricalRepairs: 1000,
      hvacMaintenance: 2000, elevatorMaintenance: 0, roofMaintenance: 1000, applianceRepairs: 1500,
      landscaping: 3600, snowRemoval: 0, poolMaintenance: 0,
      exteriorCleaning: 600, pestControl: 1200,
      propertyManagement: 8, payroll: 0, payrollTaxes: 0,
      employeeBenefits: 0, adminOffice: 1200, phonePostage: 400,
      software: 600, bankCharges: 300, creditCardProcessing: 0,
      marketing: 1500, advertising: 500, signsAndBrochures: 200,
      legalFees: 1500, accountingFees: 2000, taxPreparation: 800, consultingFees: 0,
      licensesPermits: 500, bidAssessments: 0, safetyInspections: 400, fireSprinklerInspection: 300,
      reservesForReplacement: 5000,
      securitySystems: 1800, securityPersonnel: 0,
      janitorial: 0, contractServices: 0,
      groundLease: 0, hoa: 0, otherExpenses: 1000,
      expenseGrowthRate: 2.5,
    },
    capex: {
      unitRenovationCostPerUnit: 0, unitRenovationUnitsPerYear: 0,
      unitRenovationStartYear: 1, unitRenovationRentBump: 10,
      roofReplacement: 0, hvacReplacement: 0, plumbingUpgrade: 0,
      electricalUpgrade: 0, windowReplacement: 0, elevatorModernization: 0,
      commonAreaRenovation: 0, lobbyRenovation: 0, laundryRoomUpgrade: 0,
      amenityUpgrade: 0, parkingLotResurface: 0, exteriorPaint: 0,
      signageReplace: 0, securityUpgrade: 0,
      items: [],
    },
    exit: {
      holdingPeriodYears: 5, exitCapRate: 5.5, sellingCosts: 3,
      costBasis: 1600000, landValue: 400000, depreciableLife: 27.5,
      costSegregation: false, costSegregation5yr: 0, costSegregation15yr: 0,
      taxRate: 37, longTermCapGainsRate: 20, depreciationRecaptureRate: 25,
      stateCapGainsRate: 5, netInvestmentIncomeTax: 3.8,
      is1031Exchange: false, discountRate: 8,
    },
    waterfall: {
      useWaterfall: false,
      lpEquityPct: 90, gpEquityPct: 10, preferredReturn: 8,
      catchUp: true, catchUpPct: 100,
      tier1Split: 80, tier1Hurdle: 10,
      tier2Split: 70, tier2Hurdle: 15,
      tier3Split: 60, tier3Hurdle: 20,
      acquisitionFeeToGP: 1, assetMgmtFee: 2, dispositionFee: 1,
    },
    market: {
      rentGrowthY1: 3, rentGrowthY2: 3, rentGrowthY3: 3,
      rentGrowthY4: 3, rentGrowthY5: 3, rentGrowthY6to10: 3,
      stabilizedVacancy: 5, leaseUpMonths: 0, leaseUpStartVacancy: 30,
      compAvgRent: 0, compAvgVacancy: 0, compCapRate: 0,
      marketRentGrowthForecast: 3, capRateForecast: 5.5,
      inflationRate: 3, sofrRate: 5.3,
    },
  }
}
